[package]
name = "fmt-derive"
version = "0.0.0"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmt-derive-proc = { version = "=0.0.0", path = "../fmt-derive-proc" }

[dev-dependencies]
pretty_assertions = "1.3.0"

[features]
default = ["std"]
std = []
