[package]
name = "fmt-derive"
version = "0.0.0"
readme = "README.md"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2021"
publish = ["crates-io"]
repository = "https://github.com/danielschemmel/fmt-derive"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmt-derive-proc = { version = "=0.0.0", path = "../fmt-derive-proc" }

[dev-dependencies]
pretty_assertions = "1.3.0"

[features]
default = ["std"]
std = []
