[package]
name = "fmt-derive-proc"
version = "0.0.0"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro-crate = "1"
proc-macro-error = "1"
quote = "1"
syn = { version = "1", features = [] }

[dev-dependencies]
pretty_assertions = "1"
